--- # A playbook to provision Jenkins server on Ubuntu 16.04
- name: Adding the Jenkins Public GPG key
  apt_key:
    url: https://pkg.jenkins.io/debian/jenkins-ci.org.key 
    state: present

- name: Adding Jenkins to trusted sources.list
  apt_repository: 
    repo: deb http://pkg.jenkins.io/debian-stable binary/
    state: present
    update_cache: yes

- name: Installing Jenkins
  apt: pkg=jenkins state=present update_cache=yes

- name: Starting Jenkins service
  service:
    name: jenkins
    state: started

- name: Add Oracle java apt repository key
  apt_repository:
    repo: 'ppa:webupd8team/java'

- name: Accept Oracle java license
  debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'
  changed_when: false

- name: Installing required packages
  apt: pkg={{packages}} state=present

- name: removing case sensitivity in Sql
  blockinfile:
    dest: /etc/mysql/my.cnf
    block: |
      [mysqld]
      lower_case_table_names = 1
  register: mysql_case_sensitivity

- name: flush priviliges mysql root user
  shell: >
    mysql -u root --execute "UPDATE mysql.user SET plugin = 'mysql_native_password' WHERE user = 'root'; FLUSH PRIVILEGES;"


- name: restart
  service: name=mysql state=restarted


- name: Install Uncomplicated Firewall
  apt: pkg=ufw state=present update_cache=yes

- name: Open port 8080
  ufw:
    rule: allow
    port: "{{ item }}"
  with_items:
    - "{{ ufwports }}"

- name: Enable ufw
  ufw:
    state: enabled
    policy: deny

- name: Get the jenkins-cli jarfile from the Jenkins server.
  get_url:
    url: "http://localhost:8080/jnlpJars/jenkins-cli.jar"
    dest: /home/
  register: jarfile_get
  until: "'OK' in jarfile_get.msg or 'file already exists' in jarfile_get.msg"
  retries: 5
  delay: 10
  check_mode: no

- name: Getting Initial admin password
  shell: cat /var/lib/jenkins/secrets/initialAdminPassword
  register: jenkinsadminpass

- name: Turn off Jenkins setup wizard
  lineinfile:
      dest: /etc/default/jenkins
      regexp: '^JAVA_ARGS='
      line: 'JAVA_ARGS="-Djava.awt.headless=true -Djenkins.install.runSetupWizard=false"'
      insertbefore: '^DAEMON_ARGS='
  notify: restart jenkins

- name: Adding mentioned user to jenkins
  shell: echo 'jenkins.model.Jenkins.instance.securityRealm.createAccount("{{username}}", "{{jenkinspassword}}")' | java -jar /home/jenkins-cli.jar -auth admin:"{{jenkinsadminpass.stdout}}" -s http://localhost:8080/ groovy =

- name: Installing Recommended Plugins
  shell: java -jar /home/jenkins-cli.jar -auth "{{username}}":"{{jenkinspassword}}" -s http://localhost:8080 install-plugin "{{item}}" -deploy
  with_items:
    - junit
    - postbuild-task
    - jacoco
    - test-stability
    - git
    - git-client
    - git-server
 
- name: Enabling mysql to run on boot
  service:
    name: mysql
    state: started
    enabled: true
