---   
- name: Install node, npm, pip and build-essential
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - nodejs
    - nodejs-legacy
    - npm
    - build-essential
    - python-pip
    - python3-pip

- name: create a direcotory for placing analysis scripts
  file:
    path: "/var/lib/jenkins/analysis"
    state: directory
    owner: jenkins
    mode: 0755

- name: Copy analysis script to jenkins server
  copy: 
    src: files/{{item}}
    dest: "{{jenkins_home}}/analysis/{{item}}"
  with_items:
    - package.json
    - main.js

- name: Checking if checkbox build job already exists
  shell: "java -jar /home/jenkins-cli.jar -s http://localhost:8080 list-jobs --username {{username}} --password {{jenkinspassword}}"
  register: jobs_list
  changed_when: "jobs_list.stdout.find('checkbox') == -1"

- name: Sending template for iTrust to Jenkins server
  copy:
    src: files/config.xml
    dest: /tmp/checkbox_config.xml
  when: "jobs_list.stdout.find('checkbox') == -1"

- name: Create job for checkbox.io
  shell: java -jar /home/jenkins-cli.jar -auth "{{username}}":"{{jenkinspassword}}" -s http://localhost:8080 create-job checkbox.io < /tmp/checkbox_config.xml
  when: "jobs_list.stdout.find('checkbox') == -1"
