---
- name: Main Playbook
  hosts: hosts
  gather_facts: no
  pre_tasks:
    - name: install python 2
      raw: test -e /usr/bin/python || (sudo apt -y update && sudo apt install -y python-minimal)
      changed_when: False
    - setup:
  become: yes
  vars_prompt:
    - name: username
      prompt: "Enter remote username"
      private: no
    - name: jenkinspassword
      prompt: "Enter Jenkins Admin Password"
      private: yes
  roles:
    - jenkins
    - itrust
    - checkbox